Language: en-US
Prefix: §3§l[dShop] §f
SalesTax: 25
ShowTax: true
UseShopCommand: true
DefaultShopName: Main
DisplayStockAsStack: false
DeliveryChargeScale: 1
NumberOfPlayer: 10
SaveLogs: true
CullLogs: true
LogCullAgeMinutes: 7200
LogCullTimeMinutes: 120
OnClickCloseButton_OpenStartPage: true
OpenStartPageInsteadOfDefaultShop: false
host: localhost
port: 3306
database: dynamicshopsun
username: root
password: pa55w0rd
params: '?autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull'
player_data: 'dynamicshopsun_player_data'
